footer:
  tutorial: "https://www.railstutorial.org/"
  author: "https://www.michaelhartl.com/"
contact:
  tutorial_contact: "https://www.railstutorial.org/contact"
help:
  tutorial_help: "http://www.railstutorial.org/help"
  tutorial_book: "http://www.railstutorial.org/book"
home:
  tutorial_rails: "https://www.railstutorial.org/"
  tutorial_ruby_on_rails: "https://rubyonrails.org/"
user:
  email_regex: !ruby/regexp /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  name_max: 20
  email_min: 20
  email_max: 255
  password_min: 6
  gravatar: "https://gravatar.com/emails"
password:
  reset_expired: 2
